version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: hermes_db
    environment:
      POSTGRES_DB: hermesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - hermes_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  hermes_data:
